travis:
  secure:
    BINSTAR_TOKEN: nTeCQ8vOwVSFCycpQS0718NeskAFcJg1H0dxCCUv/3vdAwr4BRAu1rcivHSfj8l47vPH0yg8Bo8EKpKebDMHMnB5NehGWxaUhNxWZwPd2eyYKQM9YBPWZYtz4HpyLIWzZR2zJfJaPkiMmi0WDDlhkG3d31utEBceven8YqG7je9Msy1GpgyxjiAGyFxJYB1rZqrLjqNL13iHgo3gVXU0rldR7tsW3jR3IxDKYEGSVB6LQxXOl/GAKdh+DD0k/SBgKLtkjHeoCvlfhmwFe9aY0k6OzbevvpiZwNQ7zuBYAjs42gNCAWYPz1GSwSpL+BT1vc9opEh+/58MHx/s0qI0W2a7cOfwtjYEK6pNa9p9cBNFLJMChxPgUn5dY7ld1Rcg7jAg9tpf2n4I3vJgVrap0qgNzaQmezXNcOR+abQFGqwzDCjrGDZTeM/28fVABlOO/dJa9q0yW7AiE2zJ6brsKMQgom/FupEDWw7cnDrmxB/BVisKRviJLaCEv6pRPtXomcJo4Ddm9BAo4TeBgdmH5x+pVv8Tyg41Znpqaht5GxV/x4mXcvLmZPRrOmGb7oUUWmPnl8N6ePA14WlecYwni3zZFKPnV3G+bHJU1eXRfISaMIoipoL1E5h6d2mxANK05JosUqamfggPKqTRUT1NBGmYBlvKKLg4ufDLrfIo4tc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
