travis:
  secure:
    BINSTAR_TOKEN: Enocl+D3YEFUiD/ngVc1/6NsQvgP0+qyFC0AN+DvPDGuwDOpyknvp8LLw7kquYdRUuoMkA0vRFPNV8xvB/8+Pn/iGnmpvM0QvrRE0HjHpqGKOSjITuPvgAquJUwA1vt8eHoqjWuu3GanJSv7JggBnOalQSBCAyMzejWWlHWeGF9JdiZkLO+VgwSovpc3ws1o9uteDSRyTxfKK98TPMVgFAO3O3HuxNElpW1NsVVvmFFvhhvCePjwfdZhYdu3VPpqvq7BAFwxIgwXSzf9VrLneSG8+axDHQncxF8rrHKQoWCD9FButlINOdbx5ttErXCM4vGA0cPqaWg60cNkcdCCxApVh2MSEotFoWK8YJFtmbQOr4ITFQxlKH/PvWFXE86LJ+KurMntDBtG07jgUWXI61E6wuiTpZpmt4IU5fCrvMhlPDhuJ/tvSeq+9pzLqLX2USm/PFwRL7y4mlBRlsNRsAyS1vs3OEcKeyK4E7uyhZPqB99bzCJD28E8HmX1AXEssT1syVLdn1iq5BRO33VkEhtRR5KXC/CubuWR0y+JgL0VnOOJt/SMTXAte5LmudsU4WlUnojZxYssR/5Spzc96PyNBAVZCVz5u6wcNO/No2VGHHUrTuqH0gX+3v7zFtXUHpvs+GMdf2Piud12l3LkEw7232on+iRgnwdZljf8NoU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
