travis:
  secure:
    BINSTAR_TOKEN: rXTnEg/aa7p9ujtzNGgg8KDWMWeacoNlzdNV3atkz7y+gH5nDBkf09Sn2UEKjialAoFoIEH/Dsw/8dD6kDemME8+EwtmG+o4Kc8D9okfizoZdP554B42sWeRePBQjPaaO3hu+xy+T1iBDkcRDgovtuNJht634zlDry45s0m+cORSdn8XP2yLGev5GkkMD+4a2FVvD3iAfDWTQTAfW6cKEa7qFYUzMbh+ncJ8unkteARl98JqsH/c9rdPitvPlVSQHLy6wwpwkIlKLRkbtsme1cJI/+06INVfEx3EaUIE/RXAhYz4u0f1uctO/g3Y0uQjLi0A6v4+lke4ZKnq532VJ5JZZJHhqEqNXaGH1YRLmsnkzzSPsCxdBy1MDlVkkQYFtD/1jCfC5BuD0DhAvtWmKeIh7iB8vm1dzi9msIqzCqVYYkcv5bOGyzOrb+ZserqY6wYYu0aCASWxzW2oRjPAZrVq0pv6tGtm9YA04j98yFKampuuZkuLCyw2ng8ikAFA/DeWSQnzlsf+vrdwrAqSjdVRh65r+G1qCGW2W+RnD1k3NGocGLMKfkk9+F1cPTtSGHwYPu4nhYz/mHzWeeS0wkhnwrBGb/Zda4laYCjFGu0wpV8bq9Evk1g7zel8UhDrd1vKPMb0QgcE5KpiNEO2Xu2jR5Zhv8+xjavBz/tkaxA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
